src/Entity/Document.php
<?php

namespace Kalitics\GedBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Document
 *
 * @ORM\Table(name="ged_document")
 * @ORM\Entity(repositoryClass="Kalitics\GedBundle\Repository\DocumentRepository")
 */
class Document
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="path", type="string", length=255)
     */
    private $path;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var \DateTime
     * @ORM\Column(name="validity", type="datetime", nullable=true)
     */
    private $validity;

    /**
     * @ORM\ManyToOne(targetEntity="Kalitics\GedBundle\Entity\DocumentType")
     * @ORM\JoinColumn(name="type_id", referencedColumnName="id")
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity="Kalitics\GedBundle\Entity\DocumentSubType")
     * @ORM\JoinColumn(name="subtype_id", referencedColumnName="id")
     */
    private $subType;

    /**
     * @ORM\ManyToOne(targetEntity="Kalitics\GedBundle\Entity\Ged", inversedBy="documents")
     * @ORM\JoinColumn()
     */
    private $ged;

    /**
     * Document constructor.
     * @param string $path
     */
    public function __construct($path)
    {
        $this->path = $path;
    }

    /**
     * @return mixed
     */
    public function getGed()
    {
        return $this->ged;
    }

    /**
     * @param mixed $ged
     */
    public function setGed($ged)
    {
        $this->ged = $ged;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return \DateTime
     */
    public function getValidity()
    {
        return $this->validity;
    }

    /**
     * @param \DateTime $validity
     */
    public function setValidity($validity)
    {
        $this->validity = $validity;
    }

    public function getWebPath()
    {
        return null === $this->path ? null : $this->getPath();
    }

    /**
     * Set path
     *
     * @param string $path
     *
     * @return Document
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Document
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    public function getWeight(){
        if(file_exists($this->getPath())){
            return filesize($this->getPath());
        }else{
            return 0;
        }
    }

    public function getDispWeight(){

        $bytes = $this->getWeight();

        if ($bytes >= 1073741824)
        {
            $bytes = number_format($bytes / 1073741824, 2) . ' GB';
        }
        elseif ($bytes >= 1048576)
        {
            $bytes = number_format($bytes / 1048576, 2) . ' MB';
        }
        elseif ($bytes >= 1024)
        {
            $bytes = number_format($bytes / 1024, 2) . ' KB';
        }
        elseif ($bytes > 1)
        {
            $bytes = $bytes . ' bytes';
        }
        elseif ($bytes == 1)
        {
            $bytes = $bytes . ' byte';
        }
        else
        {
            $bytes = '0 bytes';
        }
        return $bytes;
    }

    public function getExtension(){
        $path = $this->getPath();
        $pathElements  = new ArrayCollection(explode('.', $path));
        return $pathElements->last();
    }

    //Retour du type "Nomdocument (jpeg) Expire le 28/01/1990"
    public function __toString(){
        $this->validity != null ? $valid = "Expire le ".$this->validity->format('d/m/Y') : $valid = "";
        return $this->getName()." (".pathinfo($this->getPath(), PATHINFO_EXTENSION).") ".$valid;
    }

    public function getSubType(): ?DocumentSubType
    {
        return $this->subType;
    }

    public function setSubType(?DocumentSubType $subType): self
    {
        $this->subType = $subType;

        return $this;
    }
}

src/Entity/Ged.php
<?php

namespace Kalitics\GedBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Ged
 *
 * @ORM\Table(name="ged_ged")
 * @ORM\Entity(repositoryClass="Kalitics\GedBundle\Repository\GedRepository")
 */
class Ged
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="path", type="string", length=255, unique=false)
     */
    private $path;

    /**
     * Many GED have Many Documents.
     * @ORM\OneToMany(targetEntity="Kalitics\GedBundle\Entity\Document", mappedBy="ged")
     */
    private $documents;

    /**
     * @ORM\ManyToOne(targetEntity="Kalitics\GedBundle\Entity\DocumentCategory")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="Kalitics\GedBundle\Entity\ConfigGedCategory")
     * @ORM\JoinColumn(name="config_id", referencedColumnName="id")
     */
    private $config;

    /**
     * @var bool
     * @ORM\Column(type="boolean", options={"default":false})
     */
    private $isGalleryMode = false;

    /**
     * Ged constructor.
     * @param $documents
     */
    public function __construct($path = "")
    {
        $this->documents    = new ArrayCollection();
        $this->path         = $path;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set path
     *
     * @param string $path
     *
     * @return Ged
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPath(): ?string
    {
        return $this->path;
    }

    /**
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    /**
     * @param ArrayCollection $documents
     */
    public function setDocuments($documents): void
    {
        $this->documents = $documents;
    }

    /**
     * @param \Kalitics\GedBundle\Entity\Document $document
     */
    public function addDocument(Document $document) : void {
        if (!$this->documents->contains($document)) {
            $this->documents->add($document);
        }

        $document->setGed($this);
    }

    /**
     * @param \Kalitics\GedBundle\Entity\Document $document
     */
    public function removeDocument(Document $document) : void {
        $this->documents->removeElement($document);

        if ($document->getGed() === $this) {
            $document->setGed(null);
        }
    }

    /**
     * @return \Kalitics\GedBundle\Entity\DocumentCategory|null
     */
    public function getCategory(): ?DocumentCategory
    {
        return $this->category;
    }

    /**
     * @param \Kalitics\GedBundle\Entity\DocumentCategory|null $category
     */
    public function setCategory(
        ?DocumentCategory $category
    ) : void {
        $this->category = $category;
    }

    /**
     * @return \Kalitics\GedBundle\Entity\ConfigGedCategory|null
     */
    public function getConfig(): ?ConfigGedCategory
    {
        return $this->config;
    }

    /**
     * @param \Kalitics\GedBundle\Entity\ConfigGedCategory|null $config
     */
    public function setConfig(
        ?ConfigGedCategory $config
    ) : void {
        $this->config = $config;
    }

    /**
     * @return bool
     */
    public function isGalleryMode(): bool
    {
        return $this->isGalleryMode;
    }

    /**
     * @param bool $isGalleryMode
     */
    public function setIsGalleryMode(bool $isGalleryMode): void
    {
        $this->isGalleryMode = $isGalleryMode;
    }
}

src/Resources/views/_includes/_file_icn.html.twig
{% if file is defined %}

    {% if file.extension == 'pdf' %}
        <i class="la la-file-pdf-o"></i>
    {% elseif file.extension == 'jpg' or file.extension == 'png' or file.extension == 'jpeg' %}
        <i class="la la-file-image-o"></i>
    {% else %}
        <i class="la la-file"></i>
    {% endif %}

{% else %}
{% endif %}

src/Resources/views/_includes/_form_update.html.twig
<div id="update_document_form_container">
    {{ form_start(form) }}
        <div class="modal-header">
            <h5>Modifier le fichier</h5>
        </div>
        <div class="modal-body">
            {{ form_widget(form) }}
        </div>
        <div class="modal-footer">
            <a class="btn btn-label-danger pull-right m-l-5" data-dismiss="modal" id="closeModal">Fermer</a>
            <button type="submit" class="btn btn-label-success pull-right m-l-5">Valider</button>
        </div>
    {{ form_end(form) }}
</div>

<script>

    jQuery(document).ready(function() {

        $('#gedbundle_document_type').change(function() {
            if ($('#gedbundle_document_subtype option[data-type='+ $(this).val() +']').length) {
                $('#gedbundle_document_subtype').closest('.form-group.row').show();
            } else {
                $('#gedbundle_document_subtype').closest('.form-group.row').hide();
                $('#gedbundle_document_subtype').val('');
            }

        }).trigger('change');

        $("#update_document_form_container form").on("submit", function (){
            sendFormUpdateDocument({{ ged.id }})
            return false
        });

        $('.modal-body select').attr('style', 'width:100%;');
        $('.modal-body select').select2();
        $('.modal-body .datepicker').attr('placeholder', '15/02/2025');
        $('.modal-body .datepicker').attr('style', 'width:100%;');
    });

</script>

src/Resources/views/_includes/_gallery_files.html.twig
{#<div class="row">#}
{#    {% for document in ged.documents  %}#}
{#        <div style="position: relative;border: 1px solid red">#}
{#            <span style="position: absolute;">#}
{#                <input type="checkbox" id="docChecked" onclick="onSelectDocument({{ document.id }})">#}
{#            </span>#}

{#            <a class="img-fancy" href="{{ document | urlImage }}"  {{ (document | isDocumentAnImage) ? 'data-fancybox="images"' : '' }}>#}
{#                <img src="{{ document | urlImage }}" class="thumbnail" alt="{{ document.name }}">#}
{#            </a>#}
{#        </div>#}
{#    {% endfor %}#}
{#</div>#}
<div class="fancy_wrapper">
    {% for d in ged.documents  %}
        {% set attrs = (d | isImg) ? 'data-fancybox=images' : ''%}
        <div class="grid-item grid-item-{{ d.id }}"
             data-darkMode="{{ app.user.darkMode }}"
             id="tr_document_{{ d.id }}"
             data-remove="{{ path('kalitics_ged_document_remove', {'id' : d.id}) }}"
             data-update="{{ path('kalitics_ged_document_update', {'id' : d.id}) }}">
            <div class="checkbox-container">
                <label></label>
                <input type="checkbox" class="exportFile" data-document="{{ path('kalitics_ged_document_download', {'id' : d.id}) }}" onchange="changeNbExportFile()">
            </div>
            <div class="img_container">
                <a class="link-fancy {{ d | isPdf ? 'pdf-fancy' : '' }}" href="{{ path('kalitics_ged_document_show', {'id': d.id}) }}" {{ attrs }}>
                    <img src="{{ path('kalitics_ged_document_show', {'id': d.id, 'thumbnail': true}) }}"
                         class="thumbnail"
                         alt="{{ d.name }}">
                </a>
            </div>
            <div class="option-handler">
                <div>
                    {{ d | docIcon | raw }}
                </div>
                <div class="dropdown dropdown-inline">
                    <button type="button" class="grid-item-option" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-darkMode="{{ app.user.darkMode }}">
                        <i class="flaticon-more"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-fit dropdown-menu-md">

                        <!--begin::Nav-->
                        <ul class="kt-nav" data-isPdf="{{ d | isPdf }}">
                            <li class="kt-nav__head">
                                Changer la taille
                            </li>
                            <li class="kt-nav__separator"></li>
                            <li class="kt-nav__item">
                                <a class="kt-nav__link" data-size="small" data-doc-id="{{ d.id }}" onclick="resizeTile(this)">
                                    <i class="kt-nav__link-icon flaticon2-expand"></i>
                                    <span class="kt-nav__link-text">Petit</span>
                                </a>
                            </li>
                            <li class="kt-nav__item">
                                <a class="kt-nav__link" data-size="medium" data-doc-id="{{ d.id }}" onclick="resizeTile(this)">
                                    <i class="kt-nav__link-icon flaticon2-expand"></i>
                                    <span class="kt-nav__link-text">Moyens</span>
                                </a>
                            </li>
                            <li class="kt-nav__item">
                                <a class="kt-nav__link"  data-size="big" data-doc-id="{{ d.id }}"  onclick="resizeTile(this)">
                                    <i class="kt-nav__link-icon flaticon2-expand"></i>
                                    <span class="kt-nav__link-text">Grand</span>
                                </a>
                            </li>
                            <li class="kt-nav__separator"></li>
                            <li class="kt-nav__foot">
                                <a onClick="updateDocument({{ d.id }}, {{ ged.id }});" class="btn btn-sm btn-clean btn-icon btn-icon-md cursor-pointer" title="Modifier">
                                    <i class="la la-edit"></i>
                                </a>
                                <a href="{{ path('kalitics_ged_document_download', {'id' : d.id}) }}" class="btn btn-sm btn-clean btn-icon btn-icon-md cursor-pointer" title="Télécharger">
                                    <i class="la la-download"></i>
                                </a>
                                <a data-path="{{ path('kalitics_ged_document_download', {'id' : d.id}) }}" data-doctype="{{ d | printType }}" onclick="printDocument(this)" class="btn btn-sm btn-clean btn-icon btn-icon-md cursor-pointer" title="Imprimer">
                                    <i class="la la-print"></i>
                                </a>
                                <a onClick="deleteDocument({{ d.id }}, {{ ged.id }});" class="btn btn-sm btn-clean btn-icon btn-icon-md cursor-pointer" title="Supprimer">
                                    <i class="la la-trash"></i>
                                </a>
                            </li>
                        </ul>

                        <!--end::Nav-->
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

src/Resources/views/_includes/_ged_not_found.html.twig
Erreur de chargement de la gestion documentaire...

src/Resources/views/_includes/_list_files.html.twig
{% if ged.documents|length == 0 %}
    <div class="row">
        <div class="col-sm-12" style="text-align: center;">
            Il n'y a pas encore de document. Ajouter un document pour visualiser la liste.
            <br/>
            <br/>
            <br/>
            <i class="la la-folder-open" style="font-size: 50px;"></i>
        </div>
    </div>
{% else %}
    <div class="d-flex justify-content-between mb-3">
        <div>
            <a class="btn btn-label-success" onclick="exportFiles()">Exporter <span id="nbFileExport"></span></a>
        </div>
        <div>
            <div class="kt-checkbox-inline">
                <div class="d-flex align-items-center">
                    {% if ged.galleryMode %}
                        <i class="fas fa-th" style="font-size: 18px;margin-bottom: 5px;margin-right: 5px;"></i>
                    {% else %}
                        <i class="fas fa-list" style="font-size: 18px;margin-bottom: 5px;margin-right: 5px;"></i>

                    {% endif %}

                    <label class="kt-switch kt-switch--outline kt-switch--icon kt-switch--success">
                        <input type="checkbox" id="display_mode" name="display_mode" {{ ged.galleryMode ? "checked" : ""}} onchange="changeDisplayMode(this)">
                        <span></span>
                    </label>
                </div>
            </div>
        </div>
    </div>

    {% if not ged.galleryMode %}
        {% include '@KaliticsGed/_includes/_table_files.html.twig' %}
    {% else %}
        {% include '@KaliticsGed/_includes/_gallery_files.html.twig' %}
    {% endif %}

{% endif %}

src/Resources/views/_includes/_table_files.html.twig
<table id="get_documents_list-{{ ged.id }}" class="table table-bordered datatable">
    <thead>
    <tr>
        <th>
        </th>
        <th>Fichier</th>
        <th>Type</th>
        <th>Date de validité</th>
        <th>Poid</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for d in ged.documents %}
        {% set attrs = (d | isImg) ? 'data-fancybox=images' : ''%}
        <tr
                id="tr_document_{{ d.id }}"
                data-remove="{{ path('kalitics_ged_document_remove', {'id' : d.id}) }}"
                data-update="{{ path('kalitics_ged_document_update', {'id' : d.id}) }}"
        >
            <td>
                <label class="kt-checkbox kt-checkbox--primary" style="margin-bottom: 10px !important;">
                    <input type="checkbox"
                           class="exportFile"
                           data-document="{{ path('kalitics_ged_document_download', {'id' : d.id}) }}"
                           onchange="changeNbExportFile()">
                    <span></span>
                </label>
            </td>
            <td>
                {% include '@KaliticsGed/_includes/_file_icn.html.twig' with {'file' : d} %}
                {{ d.name }}.{{ d.extension }}
            </td>
            <td>
                {% if d.type is not null %}
                    {{ d.type.name }}
                {% else %}
                    -
                {% endif %}
            </td>
            <td>
                {% if d.validity is not null %}
                    {{ d.validity|date('d/m/Y') }}
                {% else %}
                    -
                {% endif %}
            </td>
            <td>
                {{ d.dispWeight }}
            </td>
            <td style="width: 150px;">
                <a href="{{ path('kalitics_ged_document_show', {'id' : d.id}) }}"
                   class="{{ d | isPdf ? 'pdf-fancy' : '' }} btn btn-sm btn-clean btn-icon btn-icon-md cursor-pointer"
                   title="Voir"
                   {{ attrs }}
                >
                    <i class="la la-eye"></i>
                </a>

                <a href="{{ path('kalitics_ged_document_download', {'id' : d.id}) }}" class="btn btn-sm btn-clean btn-icon btn-icon-md cursor-pointer" title="Télécharger">
                    <i class="la la-download"></i>
                </a>

                <a onClick="updateDocument({{ d.id }}, {{ ged.id }});" class="btn btn-sm btn-clean btn-icon btn-icon-md cursor-pointer" title="Modifier">
                    <i class="la la-edit"></i>
                </a>

                <a onClick="deleteDocument({{ d.id }}, {{ ged.id }});" class="btn btn-sm btn-clean btn-icon btn-icon-md cursor-pointer" title="Supprimer">
                    <i class="la la-trash"></i>
                </a>

            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

src/Resources/views/_includes/_update_modal.html.twig
<!-- Large Size -->
<div class="modal fade" id="modal_documents" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

            <div class='modal-header'><h4 class='modal-title' id='smallModalLabel'>Chargement ...</h4></div><div class='modal-body center'><div class="center p-t-50 p-b-50"><i class="fas fa-spinner fa-spin"></i></div></div>

        </div>
    </div>
</div>

src/Resources/views/_includes/_upload_file.html.twig
<form id="ged_form_{{ ged.id }}" enctype="multipart/form-data" class="bh-ged-form">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">

            <div class="form-group">
                <div class="col-sm-12">
                    <h5>Ajouter un fichier</h5>
                </div>
            </div>

            <div class="form-group bh-ged-name">
                <label class="col-sm-12 control-label" for="file_name">Nom du fichier</label>
                <div class="col-sm-12">
                    <div class="form-line">
                        <input type="text" id="file_name" name="file_name" required="required" class="form-control" placeholder="Nom du fichier">
                    </div>
                </div>
            </div>

            <div class="form-group bh-ged-type">
                <label class="col-sm-12 control-label" for="file_type_{{ ged.id }}">Type de document</label>
                <div class="col-sm-12">
                    <div class="form-line">
                        <select id="file_type_{{ ged.id }}" name="file_type" class="form-control bh-ged-type-select" style="width: 100%;">
                            {% for type in documentsTypes %}
                                <option value="{{ type.id }}">{{ type }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>


            <div class="form-group bh-ged-subtype">
                <label class="col-sm-12 control-label" for="file_subtype_{{ ged.id }}">Sous type</label>
                <div class="col-sm-12">
                    <div class="form-line">
                        <select id="file_subtype_{{ ged.id }}" name="file_subtype" class="form-control bh-ged-subtype-select" style="width: 100%;">
                            <option>- Sélectionner un sous type -</option>
                            {% for type in documentsTypes %}
                                {% for subtype in type.documentSubTypes %}
                                    <option data-type="{{ type.id }}" value="{{ subtype.id }}">{{ subtype }}</option>
                                {% endfor %}
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>


            <div class="form-group bh-ged-validity">
                <label class="col-sm-12 control-label" for="file_validity_{{ ged.id }}">Date de validité</label>
                <div class="col-sm-12">
                    <div class="form-line">
                        <input type="date" id="file_validity_{{ ged.id }}" name="file_validity" required="required" class="datepicker form-control" placeholder="Date" style="width: 100%;">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-12">
                    <div class="form-line">

                        <div id="dropzone_ged_{{ ged.id }}" data-id-ged="{{ ged.id }}" class="pull-right dz-clickable btn-block ged-dropzone" data-upload-url="{{ path('kalitics_ged_document_upload', {'id' : ged.id}) }}">
                            <div class="dz-message">
                                <div class="drag-icon-cph">

                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="54px" height="54px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon kt-svg-icon-dropzone">
                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                            <polygon id="Shape" points="0 0 24 0 24 24 0 24"/>
                                            <path d="M5.74714567,13.0425758 C4.09410362,11.9740356 3,10.1147886 3,8 C3,4.6862915 5.6862915,2 9,2 C11.7957591,2 14.1449096,3.91215918 14.8109738,6.5 L17.25,6.5 C19.3210678,6.5 21,8.17893219 21,10.25 C21,12.3210678 19.3210678,14 17.25,14 L8.25,14 C7.28817895,14 6.41093178,13.6378962 5.74714567,13.0425758 Z" id="Combined-Shape" fill="#000000" opacity="0.3"/>
                                            <path d="M11.1288761,15.7336977 L11.1288761,17.6901712 L9.12120481,17.6901712 C8.84506244,17.6901712 8.62120481,17.9140288 8.62120481,18.1901712 L8.62120481,19.2134699 C8.62120481,19.4896123 8.84506244,19.7134699 9.12120481,19.7134699 L11.1288761,19.7134699 L11.1288761,21.6699434 C11.1288761,21.9460858 11.3527337,22.1699434 11.6288761,22.1699434 C11.7471877,22.1699434 11.8616664,22.1279896 11.951961,22.0515402 L15.4576222,19.0834174 C15.6683723,18.9049825 15.6945689,18.5894857 15.5161341,18.3787356 C15.4982803,18.3576485 15.4787093,18.3380775 15.4576222,18.3202237 L11.951961,15.3521009 C11.7412109,15.173666 11.4257142,15.1998627 11.2472793,15.4106128 C11.1708299,15.5009075 11.1288761,15.6153861 11.1288761,15.7336977 Z" id="Shape" fill="#000000" fill-rule="nonzero" transform="translate(11.959697, 18.661508) rotate(-90.000000) translate(-11.959697, -18.661508) "/>
                                        </g>
                                    </svg>

                                </div>
                                <h3>Déposez ici votre fichier</h3>
                                <small>PDF, PNG, JPG < <span id="maxFileSizeDisp" class="green">15Mo</span></small>
                            </div>
                        </div>

                    </div>
                </div>
            </div>



            <div class="form-group">
                <div class="col-sm-12">
                    <input id="upload_btn_{{ ged.id }}" class="btn btn-label-success m-t-10" type="button" value="Ajouter le fichier" style="display: none; width: 100%;"/>
                </div>
            </div>


        </div>
    </div>
</form>